modLoader = "javafml"
loaderVersion = "[36,)"
license = "The MIT License (MIT)"
licenseURL= "https://github.com/GizmoTheMoonPig/luggage/blob/1.18.x/LICENSE.txt"
issueTrackerURL="https://github.com/GizmoTheMoonPig/luggage/issues"

[[mods]]
modId = "luggage"
version = "${file.jarVersion}"
displayName = "Luggage"
logoFile = "luggage.png"
credits = "Original Luggage done by Openblocks, recreated from scratch by me"
authors = "GizmoTheMoonPig"
description = '''
Brings back the Luggage entity from Openblocks.
'''

[[dependencies.luggage]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.luggage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
